export default [{
    "id": 1,
    "title": "MongoDB in Action, 2nd Edition",
    "isbn13": "9781617291609",
    "price": 19.99,
    "image": "https://pictures.abebooks.com/isbn/9788120313804-us-300.jpg",
    "category": "Fiction or Nonfiction",
    "pages": 40,
    "author": "Harper Lee",
    "desc": "An application running in the cloud can benefit from incredible  ,  security threats too. A DevOps  highest priority is     c...",
},
{
    "id": 2,
    "title": "MongoDB and Python",
    "category": "Fiction or Nonfiction",
    "pages": 160,
    "isbn13": "9781449310370",
    "price": 6.88,
    "image": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1501184571i/35839562.jpg",
    "author": "George Orwell",
    "desc": "An application running in the cloud can benefit from incredible  ,  security threats too. A DevOps  highest priority is     c...",
},
{
    "id": 3,
    "title": "Building Node Applications",
    "isbn13": "9781449337391",
    "category": "Fiction or Nonfiction",
    "pages": 30,
    "price": 4.85,
    "image": "https://images.gr-assets.com/books/1328830248l/420647.jpg",
    "desc": "An application running in the cloud can benefit from incredible  ,  security threats too. A DevOps  highest priority is     c...",
    "author": "F. Scott Fitzgerald",
},
{
    "id": 4,
    "title": "Practical MongoDB",
    "author": "Herman Melville",
    "category": "Fiction or Nonfiction",
    "pages": 150,
    "isbn13": "9781484206485",
    "price": 41.65,
    "image": "https://images-eu.ssl-images-amazon.com/images/I/51j2wLxX8uL.jpghttps://m.media-amazon.com/images/I/51jTu+hOYVL.jpg",
    "desc": "An application running in the cloud can benefit from incredible  ,  security threats too. A DevOps  highest priority is     c...",
},
{
    "id": 5,
    "title": "The Definitive Guide ",
    "author": "Herman Melville",
    "category": "Fiction or Nonfiction",
    "pages": 140,
    "isbn13": "9781484211830",
    "price": 49.99,
    "image": "https://th.bing.com/th/id/OIP.YYWTI_YKbbADvejKFOFNWAHaKe?pid=ImgDet&w=207&h=292&c=7&dpr=1.3",
    "desc": "An application running in the cloud can benefit from incredible  ,  security threats too. A DevOps  highest priority is     c...",
},
{
    "id": 6,
    "title": "MongoDB Performance Tuning",
    "author": "Herman Melville",
    "category": "Fiction or Nonfiction",
    "pages": 55,
    "isbn13": "9781484268780",
    "price": 34.74,
    "image": "https://cdn.shopify.com/s/files/1/0026/0787/4084/products/Operating_Systems_Networks_BA_3rd_Year_9789699157028-01_1024x1024.jpg?v=1538202759",
    "desc": "An application running in the cloud can benefit from incredible  ,  security threats too. A DevOps  highest priority is     c...",
},
{
    "id": 7,
    "title": "Pentaho Analytics for MongoDB",
    "author": "Herman Melville",
    "category": "Fiction or Nonfiction",
    "pages": 45,
    "isbn13": "9781782168355",
    "price": 16.99,
    "image": "https://th.bing.com/th/id/OIP.MoxPwxCXaoUd6zfucx6T9QAAAA?rs=1&pid=ImgDetMain",
    "desc": "An application running in the cloud can benefit from incredible  ,  security threats too. A DevOps  highest priority is     c...",
},
{
    "id": 8,
    "title": "Pentaho Analytics for MongoDB",
    "author": "Herman Melville",
    "category": "Fiction or Nonfiction",
    "pages": 160,
    "isbn13": "9781783553273",
    "price": 44.99,
    "image": "https://collegelearners.com/wp-content/uploads/2020/06/systems-software-leland-l-beck.jpg",
    "desc": "An application running in the cloud can benefit from incredible  ,  security threats too. A DevOps  highest priority is     c...",
},
{
    "id": 9,
    "title": "Web Development",
    "desc": "An application running in the cloud can benefit from incredible  ,  security threats too. A DevOps  highest priority is     c...",
    "author": "J.R.R. Tolkien",
    "category": "Fiction or Nonfiction",
    "pages": 160,
    "isbn13": "9781785287527",
    "price": 39.99,
    "image": "https://doku.pub/img/crop/300x300/3nl2v999op08.jpg",
    "author": "J.R.R. Tolkien",
},
{
    "id": 10,
    "title": "MongoDB Cookbook, 2nd",
    "author": "J.R.R. Tolkien",
    "category": "Fiction or Nonfiction",
    "pages": 160,
    "desc": "An application running in the cloud can benefit from incredible  ,  security threats too. A DevOps  highest priority is     c...",
    "isbn13": "9781785289989",
    "price": 44.99,
    "image": "https://4.bp.blogspot.com/-Ga-iGmWhvzo/TxgRg0-ZgiI/AAAAAAAAAOg/bErW5Dc13a4/s1600/sp.jpg",

}
]